### ISSUE TITLE
Broken install, nothing appears in window

### ISSUE THREAD

**Issue by TheLostMeme** [Y0URD34TH/Project-GLD#102]
This is what my window currently looks like, is there any way to fix this? I'm on Windows 11, but I can give more specs if needed.

![project gld window](https://github.com/Y0URD34TH/Project-GLD/assets/41345434/d2ba8f6c-0da5-4751-9bf0-83ba1fd4d09c)

**Comment by Y0URD34TH** [comment]
you prob missing some windows dependency because it's not loading fonts or anything '-'

**Comment by TheLostMeme** [comment]
> you prob missing some windows dependency because it's not loading fonts or anything '-'

i DID get an error about libcef.dll when trying to first launch the app, but after that launching it again gives the aforementioned issue. i have both directx and the VC Redist AIO package installed so i'm good there

**Comment by Y0URD34TH** [comment]
well fonts are not loading so some thing are missind and i dont have a clue '-' wich graphic cards u have

**Comment by Y0URD34TH** [comment]
and can u print gld folder?

**Comment by Y0URD34TH** [comment]
also that libcef error u  had do ur emmebr how it was?

**Comment by TheLostMeme** [comment]
1. i have a very crappy laptop so it's a Intel HD Graphics card (I assume a really old one)
2. Image is what's in the folder it installed to (unless you mean another folder)
3. Unfortunately I don't remember what the libcef.dll error was, let me reinstall real quick and see if I can get it to appear.
4.  
![gld folder](https://github.com/Y0URD34TH/Project-GLD/assets/41345434/5718b341-4429-4be5-a321-93deedd8b439)

**Comment by Y0URD34TH** [comment]
your folder seems ok

**Comment by TheLostMeme** [comment]
> your folder seems ok

the libcef error did not appear on a reinstall, i'm trying to figure out what dependency i could be missing here

**Comment by Y0URD34TH** [comment]
it doesnt seem anymore like an dependency issue for me it looks like an graphic card issue related to directx and if it is what im thinking its depth stencil messing with ui components, can u join discord and whe test it?

**Comment by Y0URD34TH** [comment]
if it is depth stencil i can ez fix the issue

**Comment by TheLostMeme** [comment]
sure, my discord is batouttahell24. lemme install discord rq

**Comment by Y0URD34TH** [comment]
https://discord.gg/FyH6Z34vcZ join

**Comment by TheLostMeme** [comment]
just joined the server
