### ISSUE TITLE
TorBox Support

### ISSUE THREAD

**Issue by Wamy-Dev** [Y0URD34TH/Project-GLD#105]
Allow using https://torbox.app rather than RealDebrid for downloading games.

TorBox is a good alternative which seeds, and is cheaper than RealDebrid.

You can read the api docs at https://api-docs.torbox.app.

You can also be featured on their integrations page here: https://torbox.app/integrations

**Comment by Y0URD34TH** [comment]
i have a question does the realdebrid api translation goes with same arguments in request etc? cause i can just pick the transltion and make an combo box that gonna change the url between torbox and realdebrid

**Comment by Y0URD34TH** [comment]
and do they return same response?

**Comment by Y0URD34TH** [comment]
sorry for the delay in the response but yeah ill give an look thx for suggesting

**Comment by Y0URD34TH** [comment]
also can i annoy u when im doing? like for testing etc?

**Comment by Wamy-Dev** [comment]
sure

**Comment by Y0URD34TH** [comment]
see dc im trying to do it rn

**Comment by Y0URD34TH** [comment]
torbox support added
