### ISSUE TITLE
Missing .DLL files

### ISSUE THREAD

**Issue by the9655a** [Y0URD34TH/Project-GLD#49]
Ive tried the preinstalled package and the regular installer .exe file, but I keep getting these errors:

![4hQJsScSJN](https://github.com/Y0URD34TH/Project-GLD/assets/149513282/0c482571-3731-4076-ba34-a4987b088840)
![mNEcEslihA](https://github.com/Y0URD34TH/Project-GLD/assets/149513282/6311eb9b-654a-42e0-ab4c-c4b51eb328fd)

**Comment by Y0URD34TH** [comment]
you need to have directx 9 installed https://www.microsoft.com/pt-br/download/details.aspx?id=35

**Comment by the9655a** [comment]
thanks, that fixed it.
