### ISSUE TITLE
Native Window controls?

### ISSUE THREAD

**Issue by Darthagnon** [Y0URD34TH/Project-GLD#50]
The current non-standard window controls don't allow me to maximise the window to fullscreen. They are also way too small on my HiDPI screen and incompatible with Aero Glass/system title bar colours. Please could you use standard window controls as offered by Windows?
![explorer_240512_67](https://github.com/Y0URD34TH/Project-GLD/assets/20792748/6a301e78-cc21-4516-a149-a94d5df63521)

**Comment by Y0URD34TH** [comment]
we opted for using and improving the default imgui tab bar for that, about the full screen button its planned to do but itll take some time

**Comment by Y0URD34TH** [comment]
the imgui tab bar give us more control than the windows one, wich is good for themes etc

**Comment by qiracy** [comment]
Hey there, we have added an option to resize GLD by adjusting the DPI value of it in update [V4.70](https://github.com/Y0URD34TH/Project-GLD/releases/tag/Update-V4.70).

While it does not utilize standard windows controls, this does allow you to make GLD significantly bigger or smaller, as well as automatically detect the best size of it based on your resolution.
